name: Norminette

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v4
    - uses: alexandregv/norminette-action@v3
      with:
        flags: './INC ./LIB/LIBFT ./LIB/muk_lib ./SRC/CLEANUP ./SRC/INITIALIZE/ ./SRC/mini_ray.c ./SRC/PARSE_RT ./SRC/RENDER ./SRC/TESTS'
